package com.mingming.agent.event;

public enum RunEventType {
    USER_MESSAGE,
    MODEL_DELTA,
    MODEL_MESSAGE,
    RETRIEVAL_RESULT,
    RAG_SYNC,
    MCP_TOOLS_BOUND,
    MCP_CONFIRM_RESULT,
    LOOP_TURN_STARTED,
    LOOP_TURN_FINISHED,
    LOOP_TERMINATED,
    TOOL_CALL,
    TOOL_RESULT,
    ERROR
}
