package com.mingming.agent.event;

public enum RunEventType {
    USER_MESSAGE,
    MODEL_DELTA,
    MODEL_MESSAGE,
    MODEL_OUTPUT,
    RETRIEVAL_RESULT,
    RAG_SYNC,
    MCP_TOOLS_BOUND,
    MCP_CONFIRM_RESULT,
    TOOL_CALL,
    TOOL_RESULT,
    TOOL_CONFIRM_REQUIRED,
    TOOL_CONFIRM_RESPONSE,
    RUN_COMPLETED,
    RUN_TERMINATED,
    ERROR
}
